name: Deploy Release to CodeDeploy

on:
  push:
    branches:
      - main
    tags:
      - 'deploytest1' # Specify the tag for the release to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Download release zip file
        run: |
          curl -sSL -o deploytest1.zip "https://github.com/Anil0192yadav/deploy-a-amazon-ec2-using-githubaction/releases/download/deploytest1/deploytest1.zip"
          ls -al
      - name: Push to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name demo \
            --deployment-group-name demo \
            --fileb://deploytest1.zip \
            --ignore-application-stop-failures

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
