name: Deploy Release to CodeDeploy

on:
  push:
    branches:
      - main
    tags:
      - 'code1' # Specify the tag for the release to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Download release zip file
        uses: softprops/action-gh-release@v1
        with:
          tag: code1
          repo: Anil0192yadav/deploy-a-amazon-ec2-using-githubaction
          filename: code1.zip

      - name: Push to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name YourCodeDeployApplicationName \
            --deployment-group-name YourDeploymentGroupName \
            --file code1.zip \
            --ignore-application-stop-failures

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: YourAWSRegion
